name: portainer

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIG_ROOT}/portainer:/data
    ports:
      - ${PORTAINER_PORT:-9000}:9000
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["NONE"]
      interval: 30s
      timeout: 10s
      retries: 3
