---
title: VeryNAS Command Center
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/homepage.png
theme: dark
color: slate
headerStyle: clean

layout:
  Media:
    style: row
    columns: 3
  Downloads:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 2
  Live Views:
    style: row
    columns: 2
